spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wh4545
    url: jdbc:mysql://localhost:3306/manage
  servlet:
    multipart:
      max-file-size: 5MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.gong.manage.system.entity, com.gong.manage.generator.entity


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

my-config:
  dir-name: D:/resource/
  base-url: http://localhost:8080/
